### ISSUE TITLE
Is this the latest version of the SIO2SD software?

### ISSUE THREAD

**Issue by a8bit** [jhusak/sio2sd_2.5_smd#1]
Hi Jakub,
I'm looking for the latest version of the SIO2SD software. This says 2.5 and I have found binaries for v3.1rc2 on http://sio2sd.gucio.pl/wiki/SoftwareAVR_en, is there a newer version of the source code available?

Cheers
Steve

**Comment by jhusak** [comment]
Hello Steve.   The last binary version is 3.1rc2 probably. But the last sources are of 2.5 version.  Version of my repo is modified to my very own pcb. Will not work with original SIO2SD.  Regards   Jakub Husak.  Dnia 17 lipca 2019 22:16 Steve Boswell &lt;notifications@github.com&gt; napisał(a):  Hi Jakub,   I&#39;m looking for the latest version of the SIO2SD software. This says 2.5 and I have found binaries for v3.1rc2 on  sio2sd.gucio.pl sio2sd.gucio.pl , is there a newer version of the source code available?  Cheers   Steve  —  You are receiving this because you are subscribed to this thread.  Reply to this email directly,  github.com view it on GitHub , or  github.com mute the thread .

**Comment by a8bit** [comment]
That's a shame, I was hoping to make a four line screen version. 

How odd to make some open source hardware but keep the firmware closed!

Thank you for replying anyway.
Steve

**Comment by jhusak** [comment]
Hello.   There is some &#34;politics&#34; in not publishing newest firmware, AFAIK.   But second thing is that there is no place in microcontroller to fit anthing in it.   However, I&#39;ll talk to Jakub Kruszona Zawadzi, the author, and see what is the current status.   Regards   Jakub Husak 
            
          
     
      
       
        Dnia 18 lipca 2019 00:52 Steve Boswell &lt;notifications@github.com&gt; napisał(a):
       
    
       
         That&#39;s a shame, I was hoping to make a four line screen version. 
 How odd to make some open source hardware but keep the firmware closed! 
 Thank you for replying anyway.  
Steve
